### ISSUE TITLE
Missing plugin exception

### ISSUE THREAD

**Issue by jaysson** [OpenFlutter/flutter_share_me#3]
I installed the plugin as usual. Calling the methods however throws missing plugin exception.

```
19:08:21.757 26 info flutter.tools [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method system on channel flutter_share_me)
19:08:21.757 27 info flutter.tools #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
19:08:21.757 28 info flutter.tools <asynchronous suspension>
19:08:21.757 29 info flutter.tools #1      FlutterShareMe.shareToSystem (package:flutter_share_me/flutter_share_me.dart:33:27)
19:08:21.757 30 info flutter.tools <asynchronous suspension>
19:08:21.757 31 info flutter.tools #2      InviteScreen.build._shareToSystem (package:entree/screens/account/invite.dart:33:15)
19:08:21.757 32 info flutter.tools #3      InviteScreen.build.<anonymous closure>.<anonymous closure> (package:entree/screens/account/invite.dart:97:49)
19:08:21.757 33 info flutter.tools #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
19:08:21.757 34 info flutter.tools #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
19:08:21.757 35 info flutter.tools #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
19:08:21.757 36 info flutter.tools #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:246:9)
19:08:21.757 37 info flutter.tools #8      TapGestureRecognizer.acceptGesture (p<…>
```

Did a clean build, still the issue persists.

**Comment by lizhuoyuan** [comment]
@

**Comment by SreehariRajeevFSS** [comment]
@lizhuoyuan  I am getting the same issue, has anyone solved this, why is this issue closed as completed?
